rules:
  no-undef:
    - warn
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-style:
    - error
    - last

env:
  jest: true
  amd: true
  es6: true

extends:
  - eslint:recommended
